# Generated by Django 3.0.3 on 2020-02-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20200206_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='librarian_id',
            new_name='librarian',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='librarian',
            old_name='location_id',
            new_name='location',
        ),
    ]
